server:
  port: 8031
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 3e170347-d013-4d8d-9f32-7afc6d5afd6b
        group: SEATA_GROUP
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/seata_lutong_stock
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
# 配置seata客户端的信息
seata:
  application-id: stock-service
  tx-service-group: stock-service-tx-group
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 3e170347-d013-4d8d-9f32-7afc6d5afd6b
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 3e170347-d013-4d8d-9f32-7afc6d5afd6b
      group: SEATA_GROUP
      username: nacos
      password: nacos
      application: seata-server