server:
  port: 8033
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: gwp
          uri: lb://product    #lb即loadbalancer，表示使用负载均衡
          predicates:
            - Path=/gw/**  #gataway表示访问网关的请求前缀
          filters:
            - StripPrefix=1     #路由转发实际路径时去掉第一个请求前缀