server:
  port: 8015
spring:
  application:
    name: sentineltest
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8090
        dashboard: 127.0.0.1:8090